CREATE DATABASE ASSIGNMENT_FIRST;

USE ASSIGNMENT_FIRST;

CREATE TABLE STUDENT_DETAILS 
				(
				STUDENTNAME varchar(30),
				COURSE varchar(15),
				MARKS int,
				DOB datetime
				);
                
INSERT INTO STUDENT_DETAILS VALUES('SHUBHAM','EDAC',85,'1995-12-21 05:12:12');

INSERT INTO STUDENT_DETAILS VALUES('RAJU','EDAC',75,'1997-11-21 05:12:00');
                